name: Sync and reset upstream repository with your current repository
description: Syncs and merges your current repository with the upstream repository using git reset --hard
author: Fredrik Simonsson

inputs:
  upstream_repo:
    description: URL of gitHub public upstream repo
    required: true
  upstream_branch:
    description: Branch to merge from upstream (defaults to downstream branch)
    required: false
    default: "master"
  downstream_branch:
    description: Branch to track
    required: false
    default: "master"
  token:
    description: GitHub Bot token
    required: true
  fetch_args:
    description: Git fetch arguments
    required: false
    default: ""
  push_args:
    description: Git push arguments, probably want to use --force here
    required: false
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.upstream_repo }}
    - ${{ inputs.upstream_branch }}
    - ${{ inputs.downstream_branch }}
    - ${{ inputs.token }}
    - ${{ inputs.fetch_args }}
    - ${{ inputs.push_args }}

branding:
  icon: "git-merge"
  color: "blue"
