name: Sync and reset upstream repository with your current repository
description: Syncs and merges your current repository with the upstream repository using git reset --hard
author: Fredrik Simonsson

inputs:
  upstream_repo:
    description: URL of gitHub public upstream repo
    required: true
  upstream_branch:
    description: Branch to merge from upstream (defaults to downstream branch)
    required: false
    default: "main"
  downstream_branch:
    description: Branch to merge into downstream
    required: false
    default: ""
  token:
    description: GitHub Bot token
    required: true
  fetch_args:
    description: Git fetch arguments
    required: false
    default: ""
  spawn_logs: 
    description: Toggle to spawn `sync-upstream-repo` with time logs
    required: true
    default: false

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.upstream_repo }}
    - ${{ inputs.upstream_branch }}
    - ${{ inputs.downstream_branch }}
    - ${{ inputs.token }}
    - ${{ inputs.fetch_args }}
    - ${{ inputs.spawn_logs }}

branding:
  icon: "git-merge"
  color: "blue"
